### ISSUE TITLE
编译 IPA

### ISSUE THREAD

**Issue by Wang-Mer** [bin64/OpenClash-Dashboard#2]
能不能 编译 一个 `.ipa`  或 `.tipa` 出来

**Comment by Wang-Mer** [comment]
应该可以借用  github 来帮助 您 的 工作

**Comment by bin64** [comment]
好的，我研究一下如何使用 GitHub 来自动编译发布，谢谢你的建议。

**Comment by bin64** [comment]
已使用 GitHub Action 发布未签名 .ipa。

**Comment by Wang-Mer** [comment]
谢谢
